export const theme = {
    colors: {
        burgundy_800: '#5F0028',
        burgundy_600: '#800035',
        burgundy_400: '#A00142',
        burgundy_200: '#DF0C64',
        burgundy_100: '#D8A9BC',
        burgundy_50: '#FFEBF3',
        navy_800: '#01043E',
        navy_600: '#0A1063',
        navy_400: '#3C418C',
        navy_300: '#888BB9',
        navy_200: '#5E66DA',
        navy_150: '#E4E6FF',
        navy_100: '#EFF0FF',
        navy_50: '#F5F5F9',
        black_800: '#0D122A',
        black_600: '#292B37',
        black_400: '#555763n',
        black_200: '#989AA4',
        black_100: '#C7C8CC',
        black_50: '#DEDFE1',
        black_20: '#F0F0F1',
        black_0: '#FFFFFF',
        black_Transparent: '#0D122A40',
        yellow_200: '#FFD800',
        yellow_100: '#FFFACC',
        green_200: '#0DBC62',
        green_100: '#CCFBD0',
        blue_200: '#18B1E7',
        blue_100: '#E8F7FD',
    },
    elevation: {
        shadow1: '0px 1px 0px 0px rgba(13, 18, 42, 0.06)',
        shadow2: '0px 4px 8px 0px rgba(13, 18, 42, 0.12)',
        shadow3: '0px 24px 40px -1px rgba(13, 18, 42, 0.16)',
    },
    space: {
        space_120: '120px',
        space_80: '80px',
        space_64: '64px',
        space_40: '40px',
        space_32: '32px',
        space_24: '24px',
        space_20: '20px',
        space_16: '16px',
        space_12: '12px',
        space_8: '8px',
        space_4: '4px',
        space_2: '2px',
        space_0: '0px',
    },
    padding: {
        p_40: '40px',
        p_24: '24px',
        p_20: '20px',
        p_16: '16px',
        p_14: '14px',
        p_12: '12px',
        p_10: '10px',
        p_8: '8px',
        p_6: '6px',
        p_4: '4px',
        p_2: '2px',
    },
    radius: {
        r_100: '100px',
        r_12: '12px',
        r_8: '8px',
        r_4: '4px',
        r_0: '0px',
    },
    typography: {
        ty_40_10: {
            fontSize: '40px',
            lineHeight: '10px',
            weight: 'bold',
        },
        ty_32_32: {
            fontSize: '32px',
            lineHeight: '32px',
            weight: 'bold',
        },
        ty_28_42: {
            fontSize: '28px',
            lineHeight: '42px',
            weight: 'bold',
        },
        ty_28_32: {
            fontSize: '28px',
            lineHeight: '32px',
            weight: 'bold',
        },
        ty_28_28: {
            fontSize: '28px',
            lineHeight: '28px',
            weight: 'bold',
        },
        ty_24_32: {
            fontSize: '24px',
            lineHeight: '32px',
            weight: 'bold',
        },
        ty_24_24: {
            fontSize: '24px',
            lineHeight: '24px',
            weight: 'bold',
        },
        ty_20_32: {
            fontSize: '20px',
            lineHeight: '32px',
            weight: 'bold',
        },
        ty_20_20: {
            fontSize: '20px',
            lineHeight: '20px',
            weight: 'bold',
        },
        ty_18_27: {
            fontSize: '18px',
            lineHeight: '27px',
            weight: 'bold',
        },
        ty_18_18: {
            fontSize: '18px',
            lineHeight: '18px',
            weight: 'bold',
        },
        ty_16_24: {
            fontSize: '16px',
            lineHeight: '24px',
            weight: 'bold',
        },
        ty_16_16: {
            fontSize: '16px',
            lineHeight: '16px',
            weight: 'bold',
        },
        ty_14_21: {
            fontSize: '14px',
            lineHeight: '21px',
            weight: 'bold',
        },
        ty_14_14: {
            fontSize: '14px',
            lineHeight: '14px',
            weight: 'bold',
        },
        ty_24_36: {
            fontSize: '24px',
            lineHeight: '36px',
            weight: 'regular',
        },
        ty_24_24: {
            fontSize: '24px',
            lineHeight: '24px',
            weight: 'regular',
        },
        ty_20_20: {
            fontSize: '20px',
            lineHeight: '20px',
            weight: 'regular',
        },
        ty_20_30: {
            fontSize: '20px',
            lineHeight: '30px',
            weight: 'regular',
        },
        ty_20_20: {
            fontSize: '20px',
            lineHeight: '20px',
            weight: 'regular',
        },
        ty_18_27: {
            fontSize: '18px',
            lineHeight: '27px',
            weight: 'regular',
        },
        ty_18_18: {
            fontSize: '18px',
            lineHeight: '18px',
            weight: 'regular',
        },
        ty_16_24: {
            fontSize: '16px',
            lineHeight: '24px',
            weight: 'regular',
        },
        ty_16_16: {
            fontSize: '16px',
            lineHeight: '16px',
            weight: 'regular',
        },
        ty_14_21: {
            fontSize: '14px',
            lineHeight: '21px',
            weight: 'regular',
        },
        ty_14_14: {
            fontSize: '14px',
            lineHeight: '14px',
            weight: 'regular',
        },
        ty_12_24: {
            fontSize: '12px',
            lineHeight: '24px',
            weight: 'regular',
        },
        ty_12_18: {
            fontSize: '12px',
            lineHeight: '18px',
            weight: 'regular',
        },
        ty_12_12: {
            fontSize: '12px',
            lineHeight: '12px',
            weight: 'regular',
        },
        ty_10_15: {
            fontSize: '10px',
            lineHeight: '15px',
            weight: 'regular',
        },
        ty_10_10: {
            fontSize: '10px',
            lineHeight: '10px',
            weight: 'regular',
        }
        
    }
}